/** Stable package API. The CLI is exposed separately through package.json. */
export { defineConfig, loadConfig } from './src/core/config.mjs';
export {
  AppProofConfigError,
  normalizeAppProofConfig,
  validateAppProofConfig,
  buildAppProofMatrix,
  appProofCaseId,
  appProofConfigHash,
  normalizeDiscoveredRoutes,
  applyAppProofCliOverrides,
} from './src/proof/app-proof.mjs';
export {
  APPROVAL_HISTORY_SCHEMA,
  APPROVAL_ENTRY_SCHEMA,
  ApprovalHistoryError,
  defaultApprovalHistoryPath,
  emptyApprovalHistory,
  readApprovalHistory,
  validateApprovalHistory,
  appendApproval,
  readVerificationEvidence,
  resolveApprovalActor,
} from './src/core/approvals.mjs';
export {
  DRIFT_BENCHMARK_SCHEMA,
  runDriftBenchmark,
  renderDriftBenchmarkHtml,
} from './src/benchmark/drift.mjs';
export { createStudioServer, startStudio } from './src/studio/server.mjs';
export { collectStudioSnapshot, readSourceExcerpt, resolveInside } from './src/studio/data.mjs';
export {
  DesignIntelligenceError,
  INTELLIGENCE_CATALOG_SCHEMA,
  INTELLIGENCE_DOMAINS,
  INTELLIGENCE_NORMALIZED_BRIEF_SCHEMA,
  INTELLIGENCE_RECOMMENDATION_SCHEMA,
  INTELLIGENCE_STACKS,
  loadIntelligenceCatalog,
  normalizeDesignBrief,
  recommendDesignDirections,
} from './src/intelligence/index.mjs';
export {
  ALLOWED_OPERATIONS,
  DEFAULT_REFERENCE_DIRECTORY,
  LICENCE_STATUSES,
  PROVENANCE_TYPES,
  REFERENCE_FILENAMES,
  REFERENCE_KINDS,
  REFERENCE_LIMITS,
  ReferenceSystem,
  ReferenceSystemError,
  ReferenceValidationError,
  assertValidReferenceArtifact,
  compareImageEvidence,
  createReferenceSystem,
  deriveHighestDeltas,
  inspectImage,
  isReferenceSystemError,
  pngPixelStats,
  scanWholeReferenceBackground,
  sha256,
  validateReferenceArtifact,
} from './src/reference/index.mjs';
export { indexRepository, discoverProofSurfaces, writeSystemGraph } from './src/system/indexer.mjs';
export {
  CODEX_CONTEXT_MAX_BYTES,
  CODEX_CONTEXT_SCHEMA,
  CODEX_INSTALL_RECEIPT_SCHEMA,
  CODEX_INTEGRATION_SCHEMA,
  CODEX_SKILL_NAME,
  CODEX_SKILL_PATH,
  CodexIntegrationError,
  buildCodexDesignContext,
  codexSkillDigest,
  codexStarterPrompt,
  codexStarterPrompts,
  inspectCodexIntegration,
  installCodexIntegration,
} from './src/codex/index.mjs';
export {
  ADAPTER_MANIFEST_SCHEMA,
  INTEGRATION_ENVELOPE_SCHEMA,
  ARTIFACT_LEDGER_SCHEMA,
  MAX_BRIDGE_LEDGER_BYTES,
  createAdapterManifest,
  validateAdapterManifest,
  createIntegrationEnvelope,
  validateIntegrationEnvelope,
  AdapterRegistry,
  BridgeRuntime,
  createBridgeRuntime,
  readArtifactLedger,
  verifyArtifactLedger,
  bridgeGitIdentity,
  bridgeConnectionContractDigest,
  builtInAdapterCatalog,
  syncBridge,
  auditBridge,
  latestBridgeEnvelope,
  ingestBridgeEnvelope,
  initializeBridgeManifest,
  safeFetch,
} from './src/bridge/index.mjs';
