/**
 * Axion's original, compact design-intelligence corpus.
 * It encodes relationships and implementation constraints, never copied UI,
 * proprietary prompts, brand assets, or third-party source code.
 */
export const INTELLIGENCE_CATALOG = Object.freeze({
  schema: 'axion-design-intelligence-catalog/v1',
  version: 1,
  domains: Object.freeze([
    'product', 'style', 'color', 'typography', 'layout', 'motion', 'icons', 'charts', 'ux',
  ]),
  stacks: Object.freeze({
    react: ['Keep state ownership explicit.', 'Split components at behavior or reuse boundaries.', 'Preserve the repository styling system.'],
    next: ['Respect server/client boundaries.', 'Keep route and loading/error conventions.', 'Do not turn the whole page into a client component.'],
    vue: ['Preserve Composition API and SFC conventions.', 'Keep props and emits explicit.', 'Reuse the repository styling system.'],
    nuxt: ['Respect server/client and route conventions.', 'Keep data fetching in the established Nuxt layer.', 'Preserve layouts and middleware.'],
    svelte: ['Preserve Svelte component and state conventions.', 'Use semantic DOM before actions.', 'Keep transitions reduced-motion safe.'],
    astro: ['Keep static content static.', 'Use islands only for real interaction.', 'Preserve content collections and routing.'],
    'html-tailwind': ['Use semantic HTML.', 'Reuse configured Tailwind tokens and variants.', 'Do not replace structure with arbitrary utility noise.'],
    shadcn: ['Reuse accessible primitives and variants.', 'Let tokens carry identity, not default component styling.', 'Preserve ownership of copied component source.'],
  }),
  intents: Object.freeze([
    {
      id: 'operations',
      signals: ['dashboard', 'admin', 'analytics', 'workflow', 'workspace', 'table', 'filter', 'monitor', 'ops', '儀表板', '後台', '分析', '工作台', '表格', '監控', '營運'],
      task: 'scan status, decide, and act repeatedly',
      statePriority: ['loading', 'empty', 'partial', 'error', 'permission', 'success'],
    },
    {
      id: 'commerce',
      signals: ['commerce', 'shop', 'store', 'catalog', 'product', 'checkout', 'pricing', 'marketplace', '電商', '商店', '商品', '型錄', '結帳', '定價', '市集'],
      task: 'compare value, build confidence, and complete a transaction',
      statePriority: ['availability', 'variant', 'validation', 'payment', 'error', 'confirmation'],
    },
    {
      id: 'editor',
      signals: ['editor', 'builder', 'canvas', 'compose', 'timeline', 'ide', 'design tool', '編輯器', '建構器', '畫布', '編輯', '時間軸', '設計工具'],
      task: 'manipulate an artifact while keeping context and history visible',
      statePriority: ['selection', 'focus', 'saving', 'saved', 'conflict', 'undo'],
    },
    {
      id: 'knowledge',
      signals: ['docs', 'documentation', 'knowledge', 'wiki', 'learning', 'course', 'reader', 'research', '文件', '知識庫', '教學', '課程', '閱讀', '研究'],
      task: 'find, understand, and retain trustworthy information',
      statePriority: ['search', 'navigation', 'progress', 'citation', 'offline', 'not-found'],
    },
    {
      id: 'marketing',
      signals: ['landing', 'marketing', 'launch', 'campaign', 'brand', 'saas', 'signup', 'conversion', '落地頁', '行銷', '發布', '活動', '品牌', '註冊', '轉換'],
      task: 'understand the promise, trust the proof, and take one primary action',
      statePriority: ['navigation', 'media-loading', 'form-validation', 'success', 'error'],
    },
    {
      id: 'portfolio',
      signals: ['portfolio', 'case study', 'studio', 'agency', 'artist', 'photographer', 'resume', '作品集', '案例', '工作室', '設計公司', '藝術家', '攝影師', '履歷'],
      task: 'recognize authorship, inspect evidence, and start a conversation',
      statePriority: ['media-loading', 'project-navigation', 'contact-validation', 'reduced-motion'],
    },
  ]),
  kernels: Object.freeze([
    {
      id: 'precision-grid', name: 'Precision Grid',
      macro: 'persistent context rail + decision canvas + bounded evidence column',
      focal: ['current decision', 'primary action', 'supporting evidence'],
      type: ['humanist sans body', 'compact grotesk labels', 'tabular numerals'],
      density: ['tight row rhythm', 'progressive disclosure', 'stable scan anchors'],
      geometry: ['4px inner rhythm', '8–12px control radius', 'one-pixel structural dividers'],
      palette: { background: '#F7F8FA', surface: '#FFFFFF', text: '#172033', muted: '#5D6678', accent: '#2457D6', border: '#D8DDE7' },
      signature: 'a slim decision rail that turns status into the next action',
      chart: 'direct-labeled lines and bars with a visible comparison baseline',
      tradeoff: 'high scan speed, with less room for cinematic expression',
    },
    {
      id: 'editorial-ledger', name: 'Editorial Ledger',
      macro: 'thesis header + numbered content bands + anchored action margin',
      focal: ['meaningful claim', 'proof or artifact', 'next step'],
      type: ['serif display for thesis', 'neutral sans for tasks', 'monospace evidence labels'],
      density: ['measured reading bands', 'dense evidence inserts', 'generous section transitions'],
      geometry: ['square evidence frames', 'soft 6px controls', 'long horizontal rules'],
      palette: { background: '#F5F0E8', surface: '#FFFDFC', text: '#211E1A', muted: '#685F55', accent: '#B33A2B', border: '#CFC5B8' },
      signature: 'numbered margin anchors connecting narrative to evidence',
      chart: 'small multiples with written takeaway and source line',
      tradeoff: 'memorable hierarchy, but requires disciplined copy length',
    },
    {
      id: 'signal-console', name: 'Signal Console',
      macro: 'command bar + modular workspace + live signal strip',
      focal: ['active object', 'available command', 'system feedback'],
      type: ['technical sans headings', 'humanist sans body', 'monospace status and values'],
      density: ['compact modules', 'layered detail panels', 'reserved breathing space around the active object'],
      geometry: ['2px focus edge', '6px modules', 'cut-corner signal markers'],
      palette: { background: '#111820', surface: '#19232D', text: '#F2F7FA', muted: '#A7B4BE', accent: '#41D6C3', border: '#35434F' },
      signature: 'a restrained signal trace that links selection, status, and history',
      chart: 'high-contrast plots with crosshair focus and redundant labels',
      tradeoff: 'strong operational identity, with a steeper visual learning curve',
    },
    {
      id: 'catalog-stage', name: 'Catalog Stage',
      macro: 'visual index + focused comparison stage + persistent decision tray',
      focal: ['chosen object', 'meaningful difference', 'commit action'],
      type: ['confident grotesk display', 'quiet sans body', 'tabular detail labels'],
      density: ['airy object stage', 'compact comparison rows', 'progressive specifications'],
      geometry: ['16px media frames', 'pill only for filters', 'crisp selection outline'],
      palette: { background: '#F3F5F2', surface: '#FFFFFF', text: '#18201A', muted: '#626E65', accent: '#146C43', border: '#D3DBD4' },
      signature: 'a decision tray that preserves comparison context across the journey',
      chart: 'comparison bars and matrices with units next to every value',
      tradeoff: 'excellent comparison clarity, with less narrative drama above the fold',
    },
    {
      id: 'spatial-chapters', name: 'Spatial Chapters',
      macro: 'asymmetric opening + spatial chapters + compact utility dock',
      focal: ['authored moment', 'supporting sequence', 'utility action'],
      type: ['display sans with extreme scale contrast', 'calm reading serif', 'small technical captions'],
      density: ['one spacious focal zone', 'rhythmic medium-density chapters', 'compact utility dock'],
      geometry: ['large image apertures', 'square text frames', 'one recurring offset edge'],
      palette: { background: '#ECE7DF', surface: '#FBF8F2', text: '#201C2A', muted: '#6A6172', accent: '#6D3FD3', border: '#C9C0CF' },
      signature: 'an offset chapter edge that becomes a repeatable navigation cue',
      chart: 'annotated editorial graphics, never decoration-only charts',
      tradeoff: 'strong authorship and recall, with more responsive art-direction work',
    },
    {
      id: 'calm-workbench', name: 'Calm Workbench',
      macro: 'task header + centered work surface + collapsible context drawers',
      focal: ['task in progress', 'editable artifact', 'secondary context'],
      type: ['warm humanist sans', 'medium-weight task headings', 'monospace metadata only'],
      density: ['balanced work surface', 'compact drawers', 'quiet empty space around manipulation targets'],
      geometry: ['10px surfaces', '4px inputs', 'low-elevation drawers'],
      palette: { background: '#F0F3F6', surface: '#FFFFFF', text: '#1E2935', muted: '#637181', accent: '#0B7285', border: '#D2DCE3' },
      signature: 'context drawers that reveal provenance without leaving the work surface',
      chart: 'calm, direct-labeled summaries with details on demand',
      tradeoff: 'low cognitive load, with restrained brand spectacle',
    },
  ]),
});

